#!/bin/bash

# Define the base path where the test result directories are located
RESULTS_PATH="/var/lib/phoronix-test-suite/test-results"

# Define the pattern for the tar.gz files
TAR_PATTERN="pts-run-*.tar.gz"

# Create the tar.gz file with the next number
TAR_FILE="$RESULTS_PATH/pts-run-result.tar.gz"
echo "Creating $TAR_FILE..."
tar -czf "$TAR_FILE" -C "$RESULTS_PATH" --exclude='*.tar.gz' .
echo "Result saved to $TAR_FILE"

